[package]
name = "raineyraine/formati"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"

description = "A simple roblox library for formatting Roblox RichText"
repository = "https://github.com/raineyraine/formati"
homepage = "https://github.com/raineyraine/formati/blob/main/README.md"

realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml", "LICENSE"]


[dependencies]

[dev-dependencies]
testez = "roblox/testez@0.4.1"
