[package]
name = "raineyraine/formati"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml", "LICENSE"]
repository = "https://github.com/raineyraine/formati"
homepage = "https://github.com/raineyraine/formati/blob/main/README.md"

[dependencies]

[dev-dependencies]
testez = "roblox/testez@0.4.1"
